/** Composable text style tokens — use with cn() */
export const text = {
  sectionTitle: "text-base font-bold text-ish-ink",
  cardTitle: "text-[15px] font-bold text-ish-ink",
  body: "text-[15px] font-medium text-ish-ink lg:text-[13.5px]",
  bodySoft: "text-[15px] text-ish-ink-soft lg:text-[13.5px]",
  caption: "text-xs text-ish-ink-soft",
  label: "text-[11px] font-semibold text-ish-ink-faint",
  metaLabel: "text-[10.5px] font-semibold text-ish-ink/55",
  metaValue: "text-[13px] font-bold text-ish-ink",
  navSection: "text-[11px] font-bold tracking-wide text-ish-ink-faint uppercase",
  navItem: "text-[15px] font-medium text-ish-ink-soft lg:text-[13.5px]",
  navItemActive: "text-[15px] font-bold text-ish-ink lg:text-[13.5px]",
  display: "text-[26px] font-extrabold text-ish-ink",
  pageTitle: "text-[17px] font-bold text-ish-ink lg:text-base",
  largeTitle: "text-[28px] font-extrabold tracking-tight text-ish-ink leading-tight",
  listTitle: "text-[16px] font-semibold text-ish-ink leading-snug",
  listSubtitle: "text-[14px] text-ish-ink-soft leading-snug",
  listMeta: "text-[13px] text-ish-ink-faint",
} as const;
